tls:
  certificates:
    - certFile: /etc/letsencrypt/live/notagar.diyor28.com/fullchain.pem
      keyFile: /etc/letsencrypt/live/notagar.diyor28.com/privkey.pem
    - certFile: /etc/letsencrypt/live/traefik.diyor28.com/fullchain.pem
      keyFile: /etc/letsencrypt/live/traefik.diyor28.com/privkey.pem
